name: 'Setup Aptos CLI'
description: 'Install the Aptos CLI'
inputs:
  version:
    description: 'Aptos CLI version to install'
    required: false
    default: '8.1.0'
runs:
  using: 'composite'
  steps:
    - name: Cache Aptos CLI
      id: cache-aptos
      uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
      with:
        path: aptos-cli
        key: aptos-cli-${{ inputs.version }}-Ubuntu-x86_64

    - name: Download Aptos CLI
      if: steps.cache-aptos.outputs.cache-hit != 'true'
      shell: bash
      env:
        APTOS_CLI_VERSION: ${{ inputs.version }}
      run: |
        mkdir -p aptos-cli
        wget -q "https://github.com/aptos-labs/aptos-core/releases/download/aptos-cli-v${APTOS_CLI_VERSION}/aptos-cli-${APTOS_CLI_VERSION}-Ubuntu-22.04-x86_64.zip"
        unzip -q "aptos-cli-${APTOS_CLI_VERSION}-Ubuntu-22.04-x86_64.zip" -d aptos-cli

    - name: Add Aptos CLI to PATH
      shell: bash
      run: |
        chmod +x aptos-cli/aptos
        echo "$(pwd)/aptos-cli" >> $GITHUB_PATH
        aptos-cli/aptos --version
