name: Tests

on:
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Forklift
            package: testsuite
          - name: TipJar
            package: example-tip-jar
          - name: Live
            package: live-tests

    name: ${{ matrix.name }} Tests

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
        cache-dependency-path: '**/package-lock.json'

    - name: Install Aptos CLI
      uses: ./.github/actions/setup-aptos-cli

    - name: Build Forklift
      working-directory: packages/forklift
      run: |
        npm ci
        npm run build

    - name: Run Tests
      working-directory: packages/${{ matrix.package }}
      env:
        APTOS_API_KEY: ${{ secrets.APTOS_API_KEY }}
      run: |
        npm ci
        npm test
